name: football
favicon: null
layout_spectrum: 0.08122855215333402
typography_spectrum: 0.6824706553015858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.19832543772645295
purpose:
  - name: follow
    item: null
    url: null
